spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/cv
        driver-class-name: org.postgresql.Driver
        username: cv_admin
        password: cv_password
    jpa:
        open-in-view: false
        properties:
            hibernate:
                ddl-auto: none
                show-sql: true
                format_sql: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    time_zone: UTC
